version: '2'
services:
  server:
    image: node:7.7.2-alpine
    working_dir: "/usr/app/"
    user: "1000:1000"
    ports:
      - 3000:3000
    volumes:
      - ./api/:/usr/app/
    command: "npm run watch"

  client:
    image: node:7.7.2-alpine
    working_dir: "/usr/app/"
    user: "1000:1000"
    ports:
      - 8081:8080
    volumes:
      - ./vuejs/:/usr/app/
    command: npm run dev -- --inline --host 0.0.0.0

  keycloak:
    image: jboss/keycloak
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NODE_ENV=development
    ports:
      - 80:80
    depends_on:
      - client
      - server
  
