version: '2'
services:
  server:
    image: node:7.7.2-alpine
    working_dir: "/usr/app/"
    user: "1000:1000"
    ports:
      - 3000:3000
    volumes:
      - ./api/:/usr/app/
    command: node src/app.js

  client:
    image: node:7.7.2-alpine
    working_dir: "/usr/app/"
    user: "1000:1000"
    ports:
      - 8080:8080
    volumes:
      - ./vuejs/:/usr/app/
    command: npm run dev -- --inline --host 0.0.0.0

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NODE_ENV=development
    ports:
      - 80:80
    depends_on:
      - client
      - server
  
